const express=require('express')
const userRouter=express.Router()
const usercontroller=require('../controllers/usercontroller')
const authcontroller=require('../controllers/authcontroller')

userRouter.get("/",usercontroller.gethomes)
userRouter.get("/search",usercontroller.searchproperties)
userRouter.get("/favourites",authcontroller.requireRole('guest'),usercontroller.getfavourites)
userRouter.get("/wishlist",authcontroller.requireRole('guest'),usercontroller.getfavourites)
userRouter.get("/bookings",authcontroller.requireRole('guest'),usercontroller.getbookings)
userRouter.post("/bookings/cancel",authcontroller.requireRole('guest'),usercontroller.cancelbooking)
userRouter.post("/addtofavourites",authcontroller.requireRole('guest'),usercontroller.addtofavourites)
userRouter.post("/removefromfavourites",authcontroller.requireRole('guest'),usercontroller.removefromfavourites)
userRouter.get("/homedetails/:id",usercontroller.gethomedetails)
userRouter.get("/properties/:id",usercontroller.gethomedetails)
userRouter.get("/book/:id",authcontroller.requireRole('guest'),usercontroller.bookhome)
userRouter.post("/confirmbooking",authcontroller.requireRole('guest'),usercontroller.confirmbooking)
userRouter.post("/reviews",authcontroller.requireRole('guest'),usercontroller.submitreview)
userRouter.get("/messages",authcontroller.requireAuth,usercontroller.getmessages)
userRouter.get("/messages/:userId",authcontroller.requireAuth,usercontroller.getconversation)
userRouter.post("/messages",authcontroller.requireAuth,usercontroller.sendmessage)
userRouter.post("/messages/read",authcontroller.requireAuth,usercontroller.markmessageasread)
module.exports=userRouter
